name: Java CI with Maven - Test and package

on: 
  pull_request:
  push:
    branches: main

jobs:
  JavaBuild:
    name: JavaBuild
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: test
        run: mvn –B package