name: Java Documentation

on: 
  pull_request:
   types:
    - closed

permissions:
  contents: write

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup java
      uses: actions/setup-java@v4
    - name: Generation doc
      run: mvn -B javadoc::javadoc
    - name: Pages
      run : peaceiris/actions-gh-pages@v4